#!/bin/bash
dir="/home/user/ritk/TASK2/blocknote-master"
extension=".py"
for file in  $(find -type f -name "*.py"); do  
    #grep -oP '(?<=import\s)\w+' $file    
     grep -oP '(?<=from\s)\w+' $file  
 done   