#!/bin/bash
#  c помощью цикла прочитать файл и вывести содержимое

set -e

read -p "Enter a path to the file " file
if [ -f "$file" ]; then 
    while IFS= read -r line; do
        echo "$line"
    done < "$file"
else
    echo "File $file does not exist :((("    
fi
