#!/bin/bash
#подсчитывает оъем диска занимаемого директорией. В качестве директории любая директория системы
set -e

read -p "Enter a path to the directory which size you are interested in: " directory
du -sh $directory